apiVersion: v1
kind: Service
metadata:
  name: hksv-service
  namespace: hksv-scrypted
spec:
  selector:
    app: hksv
  ports:
  - protocol: TCP
    port: 443
    targetPort: 10443
    name: tcp10443
  type: LoadBalancer
  loadBalancerIP: 10.100.99.135