apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hksv-config-pvc
  namespace: hksv-scrypted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "hksv-config"